# Dependency Injection Services Configuration
# Author: Ernedin Zajko <ezajko@root.ba>
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RootBa\SparkCore\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
